### PR TITLE
Game instance

### PR DESCRIPTION
**Pull request by AscendedWise**
- Fixed error in the game instance code (new pull request)
- Created the game instance (start game)
- Created the UI

### CODE REVIEW

**Comment by AscendedWise** [comment]
New pull request accidentally deleted code in the other one, causing the game instance to break.

**Review by AbubakarMohidin — DISMISSED** [review]
Good Work

**Review by AbubakarMohidin — APPROVED** [review]
approved, good work

**Review by 123Chan — DISMISSED** [review]

**Comment by AscendedWise** [comment]
Fixed all merge conflicts after rebasing merging into main

**Pull request merged**
