### PR TITLE
Renaming according to convention

### PR DESCRIPTION
**Pull request by nawarani**
All package, class, method and variable names have been refactored. I have ran the game, and tried the following to see if they work

- all piece movement
- capture
- en passant
- check
- castling
- leaderboard
- forfeit
- draw

Naming conventions used (in accordance with Java conventions)

- package names are all lowercase, multiple words becomes concatenated. i.e Frameworks_and_Drivers -> frameworksanddrivers
- Class names start with uppercase and continue in camelCase. i.e. LocationBitboard
- method and variable names start lowercase and continue in camelCase. i.e. whitePawnAttacks() and whitePawnAttacks
- constants are all uppercase separated by underscores. I have verified the use of underscore for constants with the java conventions. i.e. WHITE_PAWN

The tests currently don't run because they can't import the packages for some reason. I'm having trouble fixing this, if anyone has some time, please take a look.
Please pull and run the branch before merging to ensure none of the original functionality has been compromised.

### CODE REVIEW

**Review by AscendedWise — COMMENTED** [review]
Does 
- "Constants"
- "Pieces"
- "View"
- "Entities" 
also have to be all lower case to adhere with java conventions proper naming of packages/folders

**Comment by 123Chan** [comment]
I agree with AscendedWise for the package/folders naming. For the program and tests not running, try 

- Build->Rebuild Project

in IntelliJ.

**Review by 123Chan — APPROVED** [review]
Looks good. I like that you went back to change the naming conventions in tests as well.

**Review by 123Chan — CHANGES_REQUESTED** [review]
Check if the all the documentations are still there.

**Review by 123Chan — APPROVED** [review]
I don't see anything weird anymore. I approve.

**Pull request closed without merging**
