### PR TITLE
Pawn

### PR DESCRIPTION
**Pull request by nawarani**
Added class pawn, implementation for valid moves inprogress and added RANK 2 and 7 in FileAndRank.
Implementation not completed, code contains pseudocode still, do not merge.

### CODE REVIEW

**Comment by 123Chan** [comment]
I see it is coming along nicely. Some comments:

- Pawn does not extend Piece and does not have to be final because we can choose to extend it later on. public class Pawn implements Calculator is fine
- You have the shift backward for white and black pieces. Use << for white and >>> for black
- For moving directly forward, you have to account for enemy piece as well and not just your ally pieces
- Don't use ^ because it will mark 1s everywhere where there are pieces and not (from >>> 8)
- Use ~ instead
To account for all I said, consider combining all the chessboard to a variable pieces and writing

- valid_move &= ~pieces
for the forward movements

Getting the attacks seems good, but if you want to add those to valid moves you have to use |= and not &=.

- Consider just having valid_move variable instead of separate variables for white and black pawn valid moves. You can use if side statement to just specify how you update the valid_move variable and you can return valid_move at the end.

**Comment by AscendedWise** [comment]
Any updates on this pull request, do you need a review to merge to main?

**Comment by 123Chan** [comment]
This looks like a good start. We can work with this after we merge this in.

**Review by 123Chan — APPROVED** [review]

**Review by AbubakarMohidin — APPROVED** [review]
Thanks

**Pull request merged**
